/**
 * Apply pending Drizzle migrations to the SQLite DB.
 *
 * Usage:
 *   npm run db:migrate                       # uses ./data/zuzi.db (or DATABASE_URL)
 *   DATABASE_URL=file:/data/zuzi.db npm run db:migrate    # production target
 *
 * Migrations are SQL files in ./drizzle/, generated by `npm run db:generate`.
 * Both the schema (lib/db/schema.ts) and the generated migration files MUST be
 * committed. Drift between the two is a bug — see AGENTS.md §6.
 */

import { mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";

import Database from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { migrate } from "drizzle-orm/better-sqlite3/migrator";

const dbPath = (process.env.DATABASE_URL ?? "./data/zuzi.db").replace(
  /^file:/,
  "",
);
mkdirSync(dirname(resolve(dbPath)), { recursive: true });

const sqlite = new Database(dbPath);
sqlite.pragma("journal_mode = WAL");
sqlite.pragma("foreign_keys = ON");

const db = drizzle(sqlite);

migrate(db, { migrationsFolder: "./drizzle" });

console.log(`migrations applied to ${dbPath}`);
sqlite.close();
